name: xrgs_duplicate
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - cmake
  - ninja
  - ffmpeg
  - pillow
  - scipy
  - imageio
  - opencv
  - libxkbcommon
  - libgcc
  - libstdcxx

  # Install PyTorch + CUDA *before* pip installs ANYTHING
  - pytorch=2.3.1
  - torchvision=0.18.1
  - torchaudio=2.3.1
  - pytorch-cuda=12.1

  - pip:
      - numpy==1.26.4
      - lpips
      - trimesh
      - tyro
      - scikit-learn
      - torchmetrics[image]
      - tensorboard
      - tensorly
      - pyyaml
      - splines
      - matplotlib
      - viser
      - kaggle


      # - git+https://github.com/rahul-goel/fused-ssim@328dc9836f513d00c4b5bc38fe30478b4435cbb5
      # - git+https://github.com/nerfstudio-project/nerfview@4538024fe0d15fd1a0e4d760f3695fc44ca72787
      # - git+https://github.com/rmbrualla/pycolmap@cc7ea4b7301720ac29287dbe450952511b32125e
      # - git+https://github.com/harry7557558/fused-bilagrid@90f9788e57d3545e3a033c1038bb9986549632fe